### ISSUE TITLE
Question about 'updateKinematics'

### ISSUE THREAD

**Issue by dytan** [leggedrobotics/raisimLib#10]
Hi, little confused about the function [ArticulatedSystem::updateKinematics()](https://github.com/leggedrobotics/raisimLib/blob/master/include/raisim/object/ArticulatedSystem/ArticulatedSystem.hpp#L103). 
    
What operation it will do if call this manually ? For the situation only want the kinematics without run simulation, after call setState, 'getFramePosition' return the updated pose but 'getFrameVelocity' not change, and call 'updateKinematics' makes no difference, instead 'preContactSolverUpdate1' can update the world vel of body and frame.

**Comment by jhwangbo** [comment]
Good question. Actually you dont have to call it. setState and other methods that change the configuration will call updatekinematics automatically. It seems safe to make this method private but ill double check and then make it reflected on the next release

**Comment by dytan** [comment]
Thanks very much. But still want to know is there a way to get frame or body world velocity without run simulation? For now, I have to call pre_contact_solver_update1(GRAVITY, 0), after this getFrameVelocity will return the updated value.

**Comment by jhwangbo** [comment]
Sorry, I missed the second part of the question. you are not simulating when you call preContactSolverUpdate1. The actual integration happens in integrate2(). 

All necessary velocities are computed as part of Recursive Newton Euler (RNE), which is called in preContactSolverUpdate1(). This method is not the fastest way to get velocities but the implementation is quite efficient.

**Comment by dytan** [comment]
Got it. Thanks you.
