### ISSUE TITLE
Where Can I Display The Contact Forces !

### ISSUE THREAD

**Issue by yonchien** [leggedrobotics/raisimLib#11]
In the process of simulation , I need the contact force  data 
between the foot and the ground as the feedback  input . but I can't found the function (or the class).
where can I found Contacts Force  and how can I  Call It  
![Screenshot from 2019-09-29 16-46-14](https://user-images.githubusercontent.com/37019390/65829536-349d1080-e2d9-11e9-8ca2-720b1530dbe0.png)

**Comment by jhwangbo** [comment]
I just initiated a Q&A page in the wiki. There is an answer for you ;)
