### ISSUE TITLE
getPosition function sometimes returns NaN values

### ISSUE THREAD

**Issue by surgeonofdeath** [leggedrobotics/raisimLib#13]
I am using this library in combination with raisimGym and I developed my own Environment, but when I run more than 50 environments simultaneously (`num_envs = 50`), and query the object position using `object->getPosition(pos);`, I sometimes get NaN values in the `pos` variable.

Could you tell me why this is happening?

**Comment by jhwangbo** [comment]
Can you check if the generalized coordinate is also nan? If so, then three possibilities, 1. Your learning is unstable, 2. Your simulation is unstable (too big time step, unrealistic internal collisions) 3. Memory corruption issues
