### ISSUE TITLE
how can I define external force for box or other AS

### ISSUE THREAD

**Issue by yonchien** [leggedrobotics/raisimLib#16]
How to apply external force or torque on the box or AS

**Comment by jhwangbo** [comment]
Please check the header files. The best way to search is ctrl+F and the keyword is "setExternalForce". I tried my best to name them intuitively

**Comment by yonchien** [comment]
External Force can displayed in GUI

**Comment by jhwangbo** [comment]
do you want to see the arrow? Then you have to add a visualized object and add the arrow your self. The gui I provide is a basic example. You can easily customize it by adding objects and modifying the imgui panel

**Comment by yonchien** [comment]
I don't understand how to add a visualized object and  add the arrow . can you give me an example .
like a box apply a external force and display it , thanks
