### ISSUE TITLE
can you give an example like apply external force on the anymal 

### ISSUE THREAD

**Issue by yonchien** [leggedrobotics/raisimLib#17]
can you give an example like apply external force on the anymal ,and  show it  in the GUI.  
the force is continuous，thanks

**Comment by jhwangbo** [comment]
Sure. I'll push an example displaying a visual object on raisimOgre. An external force is too trivial. `anymal_->setExternalForce(0, {0., 0., 1.0});`
This applies force on the first link (0th) of the body, which is the base in the ANYmal model.
The API to add a visual object will change in the future. My colleague is working on cleaning it up

**Comment by jhwangbo** [comment]
the example is pushed. check the visualObject example
