### ISSUE TITLE
Heightmaps setPose (and friends) give wrong behaviour

### ISSUE THREAD

**Issue by wpumacay** [leggedrobotics/raisimLib#33]
Hi, thanks for the great physics engine. I found this issue while working with heightmaps created using data from a std::vector. Below I've attached some extra information.

* Issue: Heightmaps collision detection "stops" working when we set the position of the heightmap using either setPosition or setPose.
* OS: Ubuntu 18.04.3 LTS
* RaisimLib-version: master branch (HEAD @ dfc3d63c82d75905c3caad353d799c17899fa365)
* To reproduce: see example [heightmapFromCpp](https://github.com/wpumacay/raisimOgre/blob/issue_heightmap_pose/examples/src/primitives/heightMapFromCpp.cpp) in [this](https://github.com/wpumacay/raisimOgre/tree/issue_heightmap_pose) branch.
* Behaviour: See gifs below. When it fails, there seems to be a collider below the actual graphical object (look at the capsule in the middle as it bounces on something invisible).

**Using hm->setPosition** (collision fails)

![gif_issue_heightmaps_pose_1](https://user-images.githubusercontent.com/26859929/70285800-c3755000-1796-11ea-84c0-c49a0c0a85cd.gif)

**Using centerX, centerY**

![gif_issue_heightmaps_pose_2](https://user-images.githubusercontent.com/26859929/70285831-dc7e0100-1796-11ea-8754-53e94a65d357.gif)

This happens with both the constructor from std::vector data, and the one using TerrainProperties.

**Note:** A workaround I'm using is to set both centerX and centerY with the x-y position required, and offset all my heights by the z-position I wanted the heightmap to be. So far it works ok, but if using TerrainProperties, there's no offset parameter exposed (as in the fromPng constructor), so in that case I can't place the heightmap exactly where I need it.

**Comment by jhwangbo** [comment]
Thank you for reporting a bug. This bug is fixed in the latest commit.
