### ISSUE TITLE
How to add Mesh to World not from file but from raisim::Mesh 

### ISSUE THREAD

**Issue by geotyper** [leggedrobotics/raisimLib#35]
In Class World only one method to add mesh to world:
Mesh *addMesh(const std::string &fileName,
                double mass,
                const Mat<3, 3> &inertia,
                const Vec<3> &COM,
                double scale = 1,
                const std::string &material = "",
                CollisionGroup collisionGroup = 1,
                CollisionGroup collisionMask = CollisionGroup(-1));
Is it possible to add Mesh to World direct from class Mesh

And more question: can you plan to open source of engine?

**Comment by jhwangbo** [comment]
I just pushed the method.

Sorry, I don't have a plan to open-source the code :(
