### ISSUE TITLE
add heightmap using textfile and png 

### ISSUE THREAD

**Issue by limbryan** [leggedrobotics/raisimLib#39]
Hi, 

Have been trying for a few weeks to read in heightmaps from png and and textfile but have not been able to get it to work. Went through the source code and saw that both formats were accepted and seems the easiest to load in more complex terrain that is self defined. 

1. PNG 
tried to read in a png file that looks like the one below. Successfully compiled and loaded it.  However, in simulation, it is way too big, the the resolution seems to depend on the scale as well. 
![image](https://user-images.githubusercontent.com/46229436/73514740-d1270a80-43c0-11ea-87e5-023367a134e4.png)

![image](https://user-images.githubusercontent.com/46229436/73515130-30394f00-43c2-11ea-8f1e-1633b6d04645.png)

2. textfile
Sucessfully compiled and loaded textfile but get "insufficient number of height values" error
![image](https://user-images.githubusercontent.com/46229436/73514880-4abef880-43c1-11ea-9aba-99fcdac72968.png)

For both these formats, is there a certain format or form of png/txtfile that needs to be parsed in. Would appreciate examples of textfiles and png files that it accepts or more documentation and help on these issues if possible. 

Thank you!

**Comment by jhwangbo** [comment]
All examples are in raisimOgre repo.

An example of heightmap creation using a png is under "examples/src/primitives/heightMapFromPng.cpp". That using the raisim text format was absent but I just added it to the same file and pushed.

1. png file just defines pixel values for each coordinate. How big the map is and how high each pixel increment represents are defined by the user at the construction time. X, Y sizes are defined by "xSize" and "ySize" arguments respectively. In the case of the above black and white png file, black pixel value is 0 and white pixel value is 255. If you set the "heightScale" = 0.1, the black pixels will be 0m high and white pixels will be 25.5m high.

2. I just pushed the description of the format in the header file "World.hpp".
