### ISSUE TITLE
Some sphere have infinite rotation

### ISSUE THREAD

**Issue by geotyper** [leggedrobotics/raisimLib#42]
![raisim01](https://user-images.githubusercontent.com/30755433/74608610-b27c7f80-50f3-11ea-9377-423bc51256a6.gif)

In simple example (30 spheres and 30 cubes), find that some sphere have infinite rotation.
```
raisim::Vec<3> angulatDamp= {0.75, 0.75, 0.75};
ob->setLinearDamping(0.75);
ob->setAngularDamping(angulatDamp);
```
Need to change some parameters to stop this rotations?

**Comment by jhwangbo** [comment]
Not exactly sure why this happened but I improved the integration scheme of damping and added unit tests. This issue is probably gone now. Let me know if you still have an issue
