### ISSUE TITLE
Gravity acceleration is different for different mass

### ISSUE THREAD

**Issue by geotyper** [leggedrobotics/raisimLib#43]
Gravity acceleration is different for different mass
![Screenshot at 2020-02-16 20-20-40](https://user-images.githubusercontent.com/30755433/74609318-1a35c900-50fa-11ea-9f6b-d1fcbed36244.png)
make some spheres with mass=5.0 and cubes with mass=0.1f with near the same coordinates
and they fall to ground with different velocity(acceleration)

**Comment by jhwangbo** [comment]
do you use linear damping?

**Comment by geotyper** [comment]
yes, use linear damping=0.55

**Comment by jhwangbo** [comment]
If you use linear damping, they are not guaranteed to accelerate at the same rate. Think about a ball falling in the water

**Comment by jhwangbo** [comment]
This does not seem like a simulation issue. Closing it for now
