### ISSUE TITLE
Change mass in simulation runtime

### ISSUE THREAD

**Issue by christophecricket** [leggedrobotics/raisimLib#45]
Hi there. I have a use case where I would like to change the mass of an object in runtime. However, looking at the source code, the mass property is protected, and I can't find any function to write to it. Am I missing a method for this? Or does the API not support changing the mass in runtime? If not, can I safely just extend the class ```SingleBodyObject``` with a method to change ```mass_``` without any consequences?

**Comment by jhwangbo** [comment]
I am not sure why I missed the method but I pushed it now.
