### ISSUE TITLE
how to capture images from env

### ISSUE THREAD

**Issue by YuZhang10** [leggedrobotics/raisimLib#47]
Hi, I'm wondering how can I get img from env for CNN model training.
I'm working on a maze-solving problem with raisimGym. It looks like
![小球成功走迷宫](https://user-images.githubusercontent.com/30391848/76729081-527d0580-6793-11ea-956a-62c860fbeec0.gif)

I want the CNN model to capture the view that GUI showed, so that the agent can learn to push the ball like playing a video-game.
I found a function named copyContentsToMemory() in Orge3d, but I have no idea how to use it in raisimLib.
https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_render_target.html#a62f7ce3ddeb263e5561c8521401f4ad6

Any information or help will be appreciated.

**Comment by jhwangbo** [comment]
This is somewhat easy to do. VideoThread method is doing exactly this, copying the screen frame by frame. You can copy that method and modify. If you can make a nice and clean implementayion, please consider sending a PR. One limitation is that it cannot be in headless mode and there is unavoidable overhead.
