### ISSUE TITLE
How can I get terrain information around the robot.

### ISSUE THREAD

**Issue by ZQX323** [leggedrobotics/raisimLib#57]
Hi,

I want to capture the terrain information around the robot. For example, a 2m*2m square indicates the height of the surrounding environment. Is there any suggestion to get it? Thank you!

Best.

**Comment by jhwangbo** [comment]
Did you use the HeightMap class? then just getHeight method. Otherwise, you have to use rayTest in the world class which will be much slower

**Comment by jhwangbo** [comment]
closing this issue until I get more questions
