### ISSUE TITLE
Asking for how to set static object

### ISSUE THREAD

**Issue by ZQX323** [leggedrobotics/raisimLib#58]
Hi,

I want to add some small spheres in the space as reference motion. So I want them hang in the space without falling. I am struggling with this. Any suggestions? Besides, I want them not collide with the robot. After I set CollisionGroup and CollisionMask, it does not work, so I am a little confused to use CollisionMask. How to set it? Thank you very much!

**Comment by jhwangbo** [comment]
sphere->setBodyType(raisim::BodyType::STATIC);
But this will still allow collisions.

I didn't make documentation for collision filtering but it is standard in all physics engines. Check this Link
https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=1086

**Comment by ZQX323** [comment]
Thanks very much, it really helps!
